- hosts: all
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
      become: true
    - name: Install nginx 1.18.0
      ansible.builtin.apt:
        name: nginx=1.18.0-6ubuntu14.4
        state: present
      become: yes
    - name: Copy default.conf
      ansible.builtin.copy:
        src: ./data/default.conf
        dest: /etc/nginx/conf.d/default.conf
      become: yes
    - name: Copy certificate
      ansible.builtin.copy:
        src: ./data/linux.crt
        dest: /etc/nginx/conf.d/crt
      become: yes
    - name: Copy key
      ansible.builtin.copy:
        src: ./data/linux.key
        dest: /etc/nginx/conf.d/key
      become: yes
    - name: Copy index.html
      ansible.builtin.copy:
        src: ./data/index.html
        dest: /usr/share/nginx/html/index.html
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
