- name: Windows target
  hosts: all
  tasks:
    - name: Download nginx
      ansible.builtin.win_get_url:
        url: https://nginx.org/download/nginx-1.18.0.zip
        dest: C:/nginx.zip
    - name: Extract nginx
      ansible.builtin.win_unzip:
        src: C:/nginx.zip
        dest: C:/
    - name: Rename nginx
      ansible.builtin.win_shell: ren C:\nginx-1.18.0 nginx
      args:
        creates: C:/nginx
    - name: Copy default.conf
      ansible.builtin.copy:
        src: ./data/default.conf
        dest: C:/nginx/conf/default.conf
    - name: Copy certificate
      ansible.builtin.copy:
        src: ./data/linux.crt
        dest: C:/nginx/conf/crt
    - name: Copy key
      ansible.builtin.copy:
        src: ./data/linux.key
        dest: C:/nginx/conf/key
    - name: Copy index.html
      ansible.builtin.copy:
        src: ./data/index.html
        dest: C:/nginx/html/index.html
    - name: Download nssm
      ansible.builtin.win_get_url:
        url: https://nssm.cc/release/nssm-2.24.zip
        dest: C:/nssm.zip
    - name: Extract nssm
      ansible.builtin.win_unzip:
        src: C:/nssm.zip
        dest: C:/
    - name: Rename nssm
      ansible.builtin.win_shell: ren C:\nssm-2.24 nssm
      args:
        creates: C:/nssm
    - name:
      ansible.builtin.win_shell: |
        C:\nssm\win64\nssm.exe install nginx C:\nginx\nginx.exe
        C:\nssm\win64\nssm.exe start nginx