- name: Linux
  hosts: all
  tasks:
    - name: Copy mitmproxy-ca-cert.cer
      ansible.builtin.copy:
        src: ~/.cvex/router/mitmproxy-ca-cert.cer
        dest: /usr/local/share/ca-certificates/mitmproxy-ca-cert.crt
      become: true
    - name: Run update-ca-certificates
      ansible.builtin.command:
        cmd: update-ca-certificates
      become: true
